version: '3'
services:
  spark-master:
    image: bde2020/spark-master:2.2.0-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - "ENABLE_INIT_DAEMON=false"
    networks:
      - spark-network1
  spark-worker-1:
    image: bde2020/spark-worker:2.2.0-hadoop2.7
    container_name: spark-worker-1
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "ENABLE_INIT_DAEMON=false"
    networks:
      - spark-network1
  spark-worker-2:
    image: bde2020/spark-worker:2.2.0-hadoop2.7
    container_name: spark-worker-2
    ports:
      - "8082:8081"
    environment:
      - "ENABLE_INIT_DAEMON=false"
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - spark-network1
  zeppelin:
    image: library/dzeppelin:0.4-1
    ports:
      - "8088:8080"
      - "4040:4040"
      - "8022:22"
    networks:
      - spark-network1
    environment:
      MASTER: "spark-master"
networks:
   spark-network1:
