version: '3'
services:
  spark-master:
    hostname: spark-master
    image: localhost:5000/spark:0.4-1
    expose: 7077
    ports:
      - "8082:8080"
    networks:
      - loc
    environment:
      SPARK_MASTER_MEMORY: "4g"
      SPARK_MASTER_CORES: 2
    deploy:
      resources:
        limits:
          memory: "1g"
        reservations:
          memory: "1g"

  spark-worker:
    image: localhost:5000/spark:0.4-1
    ports:
      - "8083:8081"
    networks:
      - loc
    environment:
      MASTER: "spark-master.loc"
      SPARK_WORKER_MEMORY: "4g"
      SPARK_WORKER_CORES: 2
    deploy:
      replicas: 1
      resources:
        limits:
          memory: "2g"
        reservations:
          memory: "2g"

  zeppelin:
    hostname: zeppelin
    image: localhost:5000/zeppelin:0.4-1
    ports:
      - "8081:8080"
      - "4040:4040"
      - "8022:22"
    networks:
      - loc
    environment:
      MASTER: "sppark-master.loc"
    deploy:
      resources:
        limits:
          memory: "2g"
        reservations:
          memory: "2g"
networks:
   loc:
