---
- name: no firewalld
  yum:
    name: "firewalld"
    state: absent

- name: install docker
  yum:
    name: docker
    state: present

- name: adding user centos to docker group
  user:
    name: centos
    groups: dockerroot
    append: yes

- name: enabling docker
  become: yes
  service: name=docker.service state=started enabled=yes
