---
- name: no firewalld
  yum:
    name: "firewalld"
    state: absent

- name: add docker repo
  shell: |
     yum-config-manager --add-repo \
        https://download.docker.com/linux/centos/docker-ce.repo \
     && yum update -y && touch /etc/yum-update.done

- name: install docker
  yum:
    name: docker-ce
    state: present

- name: adding user centos to docker group
  user:
    name: centos
    groups: docker
    append: yes

- name: enabling docker
  become: yes
  service: name=docker.service state=started enabled=yes

- name: dns for docker
  become: yes
  template: src=daemon.json dest=/etc/docker/daemon.json mode=644
  notify: restart docker
