---
- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: install yum utils
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - yum-utils
    - telnet

- name: add docker repo
  shell: |
     yum-config-manager --add-repo \
        https://download.docker.com/linux/centos/docker-ce.repo \
     && yum update -y && touch /etc/yum-update.done
